name: ${project.name}
main: de.redstoneworld.redcommandsystem.RedCommandSystem
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
commands:
   redcommandsystem:
      aliases: [rcs]
      description: Main command to manage and reload the plugin.
      usage: /<command> [list|info <command>|presets|command|help|reload]
      permission: rwm.commandsystem.cmd
      permission-message: You don't have the permission <permission>
permissions:
   rwm.commandsystem.cmd:
      description: Gives permission to the plugin command
      default: op
   rwm.commandsystem.cmd.reload:
      description: Gives permission to reload the plugin
      default: op
   rwm.commandsystem.cmd.list:
      description: Gives permission to list all configured commands
      default: op
   rwm.commandsystem.cmd.info:
      description: Gives permission to get info about a configured command
      default: op
   rwm.commandsystem.cmd.presets:
      description: Gives permission to get the list of presets for a specific command
      default: op